package Models;
// Generated 2011-7-27 13:04:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Diskstatistics generated by hbm2java
 */
public class Diskstatistics  implements java.io.Serializable {


     private Integer iddiskstatistics;
     private String device;
     private Float rps;
     private Float wps;
     private Float krps;
     private Float kwps;
     private Float wait;
     private Float actv;
     private Float svct;
     private Integer w;
     private Integer b;
     private Date createtime;

    public Diskstatistics() {
    }

    public Diskstatistics(String device, Float rps, Float wps, Float krps, Float kwps, Float wait, Float actv, Float svct, Integer w, Integer b, Date createtime) {
       this.device = device;
       this.rps = rps;
       this.wps = wps;
       this.krps = krps;
       this.kwps = kwps;
       this.wait = wait;
       this.actv = actv;
       this.svct = svct;
       this.w = w;
       this.b = b;
       this.createtime = createtime;
    }
   
    public Integer getIddiskstatistics() {
        return this.iddiskstatistics;
    }
    
    public void setIddiskstatistics(Integer iddiskstatistics) {
        this.iddiskstatistics = iddiskstatistics;
    }
    public String getDevice() {
        return this.device;
    }
    
    public void setDevice(String device) {
        this.device = device;
    }
    public Float getRps() {
        return this.rps;
    }
    
    public void setRps(Float rps) {
        this.rps = rps;
    }
    public Float getWps() {
        return this.wps;
    }
    
    public void setWps(Float wps) {
        this.wps = wps;
    }
    public Float getKrps() {
        return this.krps;
    }
    
    public void setKrps(Float krps) {
        this.krps = krps;
    }
    public Float getKwps() {
        return this.kwps;
    }
    
    public void setKwps(Float kwps) {
        this.kwps = kwps;
    }
    public Float getWait() {
        return this.wait;
    }
    
    public void setWait(Float wait) {
        this.wait = wait;
    }
    public Float getActv() {
        return this.actv;
    }
    
    public void setActv(Float actv) {
        this.actv = actv;
    }
    public Float getSvct() {
        return this.svct;
    }
    
    public void setSvct(Float svct) {
        this.svct = svct;
    }
    public Integer getW() {
        return this.w;
    }
    
    public void setW(Integer w) {
        this.w = w;
    }
    public Integer getB() {
        return this.b;
    }
    
    public void setB(Integer b) {
        this.b = b;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }




}


